#!/bin/bash -e

DESTDIR=$1
if [ -z "$DESTDIR" ]; then
  echo "Syntax: $0 <dest-dir>" 1>&2
  exit 1
fi
if [ ! -d "$DESTDIR" ]; then
  mkdir $DESTDIR
fi

PYTHON=$(which python3)
if [ -z "$PYTHON" ]; then
  PYTHON=$(which python)
fi

virtualenv -p $PYTHON $DESTDIR
source $DESTDIR/bin/activate

# See issue #2705: "How to generate a zip file with deps for AWS Lambda"
# <https://github.com/pypa/pipenv/issues/2705>
pip install pipenv
PIPENV_VERBOSITY=-1 pipenv requirements > build-in-venv.txt
pip install -r build-in-venv.txt
rm -f build-in-venv.txt
