#!/bin/bash -e

DESTDIR=$1
if [ -z "$DESTDIR" ]; then
  echo "Syntax: $0 <dest-dir>" 1>&2
  exit 1
fi
if [ ! -d "$DESTDIR" ]; then
  mkdir $DESTDIR
fi

virtualenv -p $(which python) $DESTDIR
source $DESTDIR/bin/activate

# See issue #2705: "How to generate a zip file with deps for AWS Lambda"
# <https://github.com/pypa/pipenv/issues/2705>
pip install pipenv
pipenv lock -r > build-in-venv.txt
pip install -r build-in-venv.txt
rm -f build-in-venv.txt