#!/bin/bash -e

DESTDIR=$1
if [ -z "$DESTDIR" ]; then
  echo "Syntax: $0 <dest-dir>" 1>&2
  exit 1
fi
if [ ! -d "$DESTDIR" ]; then
  mkdir $DESTDIR
fi

virtualenv $DESTDIR
source $DESTDIR/bin/activate
pip install -r requirements.txt
