#!/usr/bin/env python
#
# Copyright 2017 Richard Dawe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import twitter
from sparkpost import SparkPost
import random
import json

def FetchConfig():
    configfile = open("config.json")
    return json.load(configfile)

config = FetchConfig()

# XXX: Support getting these from enviroment variables again.
# And/or a configuration file that doesn't contain rest of settings.
#
#twitter_consumer_key=os.environ.get('TWITTER_CONSUMER_KEY')
#twitter_consumer_secret=os.environ.get('TWITTER_CONSUMER_SECRET')
#twitter_access_token_key=os.environ.get('TWITTER_ACCESS_TOKEN_KEY')
#twitter_access_token_secret=os.environ.get('TWITTER_ACCESS_TOKEN_SECRET')
#
#sparkpost_api_key=os.environ.get('SPARKPOST_API_KEY')

twitter_consumer_key=config["twitter_consumer_key"]
twitter_consumer_secret=config["twitter_consumer_secret"]
twitter_access_token_key=config["twitter_access_token_key"]
twitter_access_token_secret=config["twitter_access_token_secret"]

sparkpost_api_key=config["sparkpost_api_key"]

# XXX: how do I ship an app with this consumer key+secret so no-one can decode them?
api = twitter.Api(consumer_key=twitter_consumer_key,
                  consumer_secret=twitter_consumer_secret,
                  access_token_key=twitter_access_token_key,
                  access_token_secret=twitter_access_token_secret)

sp = SparkPost(sparkpost_api_key)

#print(api.VerifyCredentials())

# XXX: Allow retweets to be skipped?
def FetchTweets(config):
    results=[]

    for screen_name in config['screen_names']:
        # XXX: Fetch user name from API
        user = api.GetUser(screen_name=screen_name)
        name = user.name
        statuses = api.GetUserTimeline(screen_name=screen_name, count=config['fetch_per_user'])
        chosen = random.sample(statuses, config['select_per_user'])
        results.append({ 'screen_name': screen_name, 'name': name, 'chosen': chosen })

    return results

# Some choice messages of the day
def FetchMOTDs():
    # Source: https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing
    networkFallacies = [
        "1. The network is reliable.",
        "2 Latency is zero.",
        "3. Bandwidth is infinite.",
        "4. The network is secure.",
        "5. Topology doesn't change.",
        "6. There is one administrator.",
        "7. Transport cost is zero.",
        "8. The network is homogeneous.",
    ]
    return {
        "Fallacy of Distributed Computing": random.choice(networkFallacies)
    }

# XXX: Nicer formatting (w/ images?) for tweets
def FormatMessages(config, tweets, motds):
    # XXX: Datestamp in subject
    subject='Digests for Thought: Random tweets'

    text='\n'
    html='''
<html>
<head><title>%s</title></head>
<body>
''' % (subject)

    for m in motds:
        text += "%s: %s\n\n" % (m, motds[m])
        html += "<p><b>%s:</b> %s</p>\n\n" % (m, motds[m])

    for r in tweets:
        text += "%s (%s)\n\n" % (r['screen_name'], r['name'])
        html += "<p><b>@%s (%s)</b></p>\n" % (r['screen_name'], r['name'])
        html += "<p><ul>\n"

        for s in r['chosen']:
            # XXX: Eat whitespace in text
            link = "https://twitter.com/%s/status/%s" % (s.user.screen_name, s.id_str)
            # Click tracking is really distracting for links in the text part,
            # so disable click tracking. Also, use a pipe separator
            # to work around an apparent bug where link-attr seems to be ignored
            # in the link parser: "[ link[[link-attr]] ]" doesn't seem to work.
            text += " * %s | %s[[data-msys-clicktrack=\"0\"]]\n" % (s.text, link)
            html += '<li>%s [ <a href="%s">View tweet</a> ]</li>\n' % (s.text, link)

        text += '\n'
        html += '</ul></p>\n'

    html += '''
</body>
</html>
'''

    if config['debug']:
        print(text)
        print(html)

    return { 'subject': subject, 'text': text, 'html': html }

def handler(event, context):
    config = FetchConfig()
    tweets = FetchTweets(config)
    motds = FetchMOTDs()
    formatted = FormatMessages(config, tweets, motds)

    response = sp.transmissions.send(
        recipients=config['recipients'],
        from_email=config['sender'],
        subject=formatted['subject'],
        text=formatted['text'],
        html=formatted['html']
    )

    # Convert this into success/failure
    print(response)

if __name__ == "__main__":
    handler(None, None)

